---
name: CI

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master
      - 'release'

jobs:
  build:
    name: build
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.8

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - uses: actions/setup-python@v2
        with:
          python-version: '3.7.x'

      - name: setup env
        run: make ci-report

      - name: shellcheck
        run: make shellcheck

      - name: lint
        run: make lint

      - name: install requirements
        run: make deps fpm package_cloud

      - name: build
        run: CIRCLECI=true make build

      - name: bash tests
        run: basht tests/**/tests.sh

      - name: upload packages
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build


  unit-tests:
    name: unit.${{ matrix.buildpack }}
    needs: build
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        buildpack:
          - buildpack-clojure
          - buildpack-go
          - buildpack-gradle
          - buildpack-java
          - buildpack-multi
          - buildpack-nodejs
          - buildpack-null
          - buildpack-php
          - buildpack-play
          - buildpack-python
          - buildpack-ruby
          - buildpack-scala
          - buildpack-static
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.8

      - name: download packages
        uses: actions/download-artifact@v1
        with:
          name: build

      - name: install requirements
        run: make deps

      - name: build docker images
        run: make build/docker

      - name: run buildpack test
        run: |
          echo "executing ${{ matrix.buildpack }} tests"
          basht buildpacks/${{ matrix.buildpack }}/tests/*/test.sh

  release:
    name: release
    needs: unit-tests
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: download packages
        uses: actions/download-artifact@v1
        with:
          name: build

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: release
        run: |
          if [[ "${GITHUB_REF#refs/heads/}" == "release" ]]; then
            export CI_BRANCH=${GITHUB_REF#refs/heads/}
            export PACKAGECLOUD_REPOSITORY=dokku/dokku
            make release release-packagecloud
          fi
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
